annotations:
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: "1.2"
dependencies:
- condition: kic-crds.enabled
  name: kic-crds
  repository: ""
  version: 3.2.0
- condition: gwapi-standard-crds.enabled
  name: gwapi-standard-crds
  repository: ""
  version: 1.0.0
- condition: gwapi-experimental-crds.enabled
  name: gwapi-experimental-crds
  repository: ""
  version: 1.0.0
description: Deploy Kong Gateway Operator
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
- email: team-k8s@konghq.com
  name: team-k8s-bot
name: gateway-operator
sources:
- https://github.com/Kong/charts/tree/main/charts/gateway-operator
version: 0.1.9
